### ISSUE TITLE
EXOS-Qt package for Linux

### ISSUE THREAD

**Issue by erseco** [exoeconomy/EXOS-Qt#17]
Hi guys, do you have plans to release a package for Linux?

**Comment by turcol** [comment]
Yes, we will be releasing it very soon

**Comment by turcol** [comment]
The executable for linux is now under the [release tab](https://github.com/exoeconomy/EXOS-Qt/releases/tag/v2.0.0.1) or directly from [here](https://github.com/exoeconomy/exos-qt/releases/download/v2.0.0.1/EXOS-Qt-v2.0.0.1-x86_64.AppImage)

Once you have downloaded it, make the file executable with the next command (or from the GUI properties)
```
$ chmod a+x EXOS-Qt-v2.0.0.1-x86_64.AppImage
$ ./EXOS-Qt-v2.0.0.1-x86_64.AppImage &
```

**Comment by erseco** [comment]
Nice, thanks @turcol I'm clossing this issue
