### ISSUE TITLE
Digitally sign apps

### ISSUE THREAD

**Issue by erseco** [exoeconomy/EXOS-Qt#18]
Hi @turcol many users are asking me about how to disabling the gatekeeper in Mac, as well in Windows, opening the wallet says that is insecure, a good practice can register an Apple Developer ID to sign the MacOS app (same for the Windows one).

In the next major release, Apple is planning to not allow running non-signed apps so we shall consider it

**Comment by turcol** [comment]
Hi @erseco this is something we are looking at the moment for the next release of binaries. 

In the meantime, the first time you open the app in macOS, right-click on the icon, and it will give you the option **open** without disabling completely the gatekeeper. This is needed only the first time you open the app; after that, you will only double click on the app.
