### ISSUE TITLE
Apple Silicon (M1) compatibility

### ISSUE THREAD

**Issue by erseco** [exoeconomy/EXOS-Qt#26]
Have you plans to offer a universal binary for macOS compatible with the new M1 processor?

**Comment by turcol** [comment]
We are not planning to have more releases for the Qt Wallet for any OS. The process to phase-off the Qt wallet already started and the Qt will be replaced for the EXOS Core Wallet. You can download it from https://github.com/exoeconomy/EXOS-Core/releases

**Comment by erseco** [comment]
Thanks, @turcol, how can I migrate our wallets from Qt wallet to the new one? Because in Qt we don't have the "secure words" like in cloud wallet.

**Comment by turcol** [comment]
Sent your tokens from your Qt wallet to your newly created wallet on the EXOS Core wallet

**Comment by royvella** [comment]
10:47: "start-daemon: /Applications/EXOS Core.app/Contents/resources/daemon/publishRocksDb/Blockcore.Node"

10:47: "LAUNCH: /Applications/EXOS Core.app/Contents/resources/daemon/publishRocksDb/Blockcore.Node"

10:47: "ARGS: [\"-port=4562\",\"-rpcport=4561\",\"-apiport=39120\",\"-wsport=39120\",\"-dbtype=rocksdb\",\"--chain=EXOS\"]"

10:47: "Starting daemon with parameters: -port=4562,-rpcport=4561,-apiport=39120,-wsport=39120,-dbtype=rocksdb,--chain=EXOS"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.FullNode[0]\n \n -- \n ./yNMs \n -MMMMMs \n -MMMMMs \n -MMMMMs \n -M"

10:47: "EXOS Node: MMMMs `` \n -MMMMMs /my/.` \n -MMMMMs /MMMNds:. \n -MMMMMs /MMMMMMMmh+- \n -MMMMMs `:sdNMMMMMMM. _ _ _ _ _ _ _ \n -MMMMMs `-/mMMMMM. |_) | / \\ / |/ / / \\ |_) |_ \n -MMMMMs yMMMMM. |_) |_ \\_/ \\_ |\\ \\_ \\_/ | \\ |_ \n -MMMMMs yMMMMM. www.blockcore.net\n -MMMMMh-` `:dMMMMM. \n -MMMMMMNmy/..+ymMMMMMMM. Full Consensus Validating Node\n `/ymMMMMMMMNNMMMMMMMmy/ \n `-ohNMMMMMMMMNh+-` \n `:smMMds:` \n ..\n \n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.FullNode[0]\n Full node initialized on EXOSMain.\n"

10:47: "EXOS Node: \nApplication starting, press Ctrl+C to cancel.\n\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.FullNode[0]\n Starting node.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Features.NodeHost.NodeHostFeature[0]\n NodeHost listening on: \n http://localhost:39120/\n - UI: True\n - API: True\n - WS: False\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n Broadcast WalletInfoBroadcaster starting in 10 seconds.\n\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n Broadcast StakingBroadcaster starting in 10 seconds.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Base.BaseFeature[0]\n Loading finalized block height.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Base.BaseFeature[0]\n Loading chain.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Base.BaseFeature[0]\n Chain loaded at height 0.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n FlushChain starting in 60 seconds.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n Periodic peer flush starting in 300 seconds.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Features.MemoryPool.MempoolManager[0]\n Loading Memory Pool.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n MemoryPool.RelayWorker starting in 10 seconds.\n\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n Notify starting.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Features.RPC.RPCFeature[0]\n RPC Server is off based on configuration.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n Wallet persist job starting in 300 seconds.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Features.Wallet.WalletSyncManager[0]\n WalletSyncManager initialized. Wallet at block 0.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Features.Wallet.AddressBook.AddressBookManager[0]\n A new address book was created.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n DiscoverFromDnsSeedsAsync starting.\n\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n DiscoverPeersAsync starting.\n"

10:47: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n PeerConnectorAddNode.ConnectAsync starting.\n\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n PeerConnectorDiscovery.ConnectAsync starting.\n"

10:47: "EXOS Node: \u001b[41m\u001b[1m\u001b[37mcrit\u001b[39m\u001b[22m\u001b[49m: Blockcore.Connection.ConnectionManager[0]\n Unable to listen on port 4562 (you can change the port using '-port=[number]'). Error message: Address already in use\n"

10:47: "EXOS Node: There was a problem initializing the node. Details: 'System.Net.Sockets.SocketException (48): Address already in use\n at Blockcore.Connection.ConnectionManager.StartNodeServer() in /Users/sergioquintero/Downloads/blockcore/src/Blockcore/Connection/ConnectionManager.cs:line 215\n at Blockcore.Connection.ConnectionManager.Initialize(IConsensusManager consensusManager) in /Users/sergioquintero/Downloads/blockcore/src/Blockcore/Connection/ConnectionManager.cs:line 158\n at Blockcore.FullNode.Start() in /Users/sergioquintero/Downloads/blockcore/src/Blockcore/FullNode.cs:line 226\n at Blockcore.Utilities.FullNodeExtensions.RunAsync(IFullNode node, CancellationToken cancellationToken) in /Users/sergioquintero/Downloads/blockcore/src/Blockcore/Utilities/FullNodeExtensions.cs:line 92\n at Blockcore.Utilities.FullNodeExtensions.RunAsync(IFullNode node) in /Users/sergioquintero/Downloads/blockcore/src/Blockcore/Utilities/FullNodeExtensions.cs:line 54\n at Blockcore.Node.Program.Main(String[] args)'\n"

10:47: "EXOS Node: Application is shutting down...\n"

10:47: "EXOS Node: The CancellationTokenSource has been disposed.\n"

10:47: "EXOS Node daemon process exited with code 0 and signal null when the state was 1."

10:47: "CRITICAL: EXOS Node daemon process exited during startup with code 0 and signal null."

Thanks,

Roy

**Comment by turcol** [comment]
@royvella thanks for your feedback. Please download the latest EXOS Core release from here:
  https://github.com/exoeconomy/EXOS-Core/releases

Thank you

**Comment by royvella** [comment]
Nayib,

Same error:

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Base.BaseFeature[0]\n Loading chain.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Base.BaseFeature[0]\n Chain loaded at height 0.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n FlushChain starting in 60 seconds.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n Periodic peer flush starting in 300 seconds.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Features.MemoryPool.MempoolManager[0]\n Loading Memory Pool.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n MemoryPool.RelayWorker starting in 10 seconds.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n Notify starting.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Features.RPC.RPCFeature[0]\n RPC Server is off based on configuration.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n Wallet persist job starting in 300 seconds.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Features.Wallet.WalletSyncManager[0]\n WalletSyncManager initialized. Wallet at block 0.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.Features.Wallet.AddressBook.AddressBookManager[0]\n Address book was loaded.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n DiscoverPeersAsync starting.\n\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n DiscoverFromDnsSeedsAsync starting.\n"

09:46: "EXOS Node: \u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n PeerConnectorAddNode.ConnectAsync starting.\n\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Blockcore.AsyncWork.AsyncProvider[0]\n PeerConnectorDiscovery.ConnectAsync starting.\n"

09:46: "EXOS Node: \u001b[41m\u001b[1m\u001b[37mcrit\u001b[39m\u001b[22m\u001b[49m: Blockcore.Connection.ConnectionManager[0]\n Unable to listen on port 4562 (you can change the port using '-port=[number]'). Error message: Address already in use\n"

09:46: "EXOS Node: There was a problem initializing the node. Details: 'System.Net.Sockets.SocketException (48): Address already in use\n at Blockcore.Connection.ConnectionManager.StartNodeServer() in /Users/sergioquintero/Downloads/blockcore/src/Blockcore/Connection/ConnectionManager.cs:line 215\n at Blockcore.Connection.ConnectionManager.Initialize(IConsensusManager consensusManager) in /Users/sergioquintero/Downloads/blockcore/src/Blockcore/Connection/ConnectionManager.cs:line 158\n at Blockcore.FullNode.Start() in /Users/sergioquintero/Downloads/blockcore/src/Blockcore/FullNode.cs:line 226\n at Blockcore.Utilities.FullNodeExtensions.RunAsync(IFullNode node, CancellationToken cancellationToken) in /Users/sergioquintero/Downloads/blockcore/src/Blockcore/Utilities/FullNodeExtensions.cs:line 92\n at Blockcore.Utilities.FullNodeExtensions.RunAsync(IFullNode node) in /Users/sergioquintero/Downloads/blockcore/src/Blockcore/Utilities/FullNodeExtensions.cs:line 54\n at Blockcore.Node.Program.Main(String[] args) in /Users/sergioquintero/Downloads/blockcore/src/Node/Blockcore.Node/Program.cs:line 34'\n"

09:46: "EXOS Node: Application is shutting down...\n"

09:46: "EXOS Node: The CancellationTokenSource has been disposed.\n"

09:46: "EXOS Node daemon process exited with code 0 and signal null when the state was 1."

09:46: "CRITICAL: EXOS Node daemon process exited during startup with code 0 and signal null."

09:46: "Retrying 2..."

09:46: "GET \"http://localhost:39120/api/node/status\"\n failed in 8 ms."

09:46: "Retrying 3..."

09:46: "GET \"http://localhost:39120/api/node/status\"\n failed in 7 ms."

09:46: "Checking for update..."

09:46: "Retrying 4..."

09:46: "GET \"http://localhost:39120/api/node/status\"\n failed in 4 ms."

09:47: "Retrying 5..."

09:47: "GET \"http://localhost:39120/api/node/status\"\n failed in 4 ms."

09:47: "Retrying 6..."

09:47: "GET \"http://localhost:39120/api/node/status\"\n failed in 32 ms."

Thanks,

Roy
